# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867d8b2fcbe8770f2edf7547e4682f0e3a109c64df2cdcb1dd27c00b76d22b11e7bb76171d0eca167dbecaa80b9c02653fe72172a389e5ec707bd62bbab398f6

test:
  secret_key_base: 022de92ab304325c785c8d2b607ffe0db528f7bf72febaaddeda2f2c65a881f4feadf4ab2ca31ea7680621703cdfd3753b556fbb25d3e19ab98c02ce705db735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
